spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-gao-dev
---
spring:
  profiles: sit   #测试环境
  application:
    name: microservicecloud-config-gao-test